# Generated by Django 5.2 on 2025-04-09 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_question_likes_question_likes_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='likes_count',
        ),
    ]
