# Generated by Django 5.2 on 2025-05-28 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('main', '0005_question_dislikes_question_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddField(
            model_name='question',
            name='dislikes_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='likes_count',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['created_at'], name='main_answer_created_e135b1_idx'),
        ),
        migrations.AddIndex(
            model_name='answer',
            index=models.Index(fields=['question'], name='main_answer_questio_6fbbcc_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['created_at'], name='main_questi_created_421617_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['likes_count'], name='main_questi_likes_c_e7e687_idx'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['dislikes_count'], name='main_questi_dislike_9c4982_idx'),
        ),
        migrations.AddIndex(
            model_name='tag',
            index=models.Index(fields=['title'], name='main_tag_title_329360_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['username'], name='main_user_usernam_b7ac05_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='main_user_email_6be720_idx'),
        ),
    ]
